server:
  port: 7776
eureka:
 client:

    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7776/eureka/
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: 123456
  freemarker:
    prefer-file-system-access: false