server:
  port: 7776
eureka:
  client:
    service-url:
      defalutZone: http://localhost:7776/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: 123456
  freemarker:
    prefer-file-system-access: false